version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sample_app
    ports:
      - '5050:5050'
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5050/login"]
      interval: 30s
      timeout: 10s
      retries: 3

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins_server
    ports:
      - '8080:8080'
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
    user: root
    networks:
      - app_network
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_data:

networks:
  app_network:
    driver: bridge